lxde/libfm

- src/modules/vfs-search.c
This commit definitely fixes https://github.com/lxde/lxqt/issues/1058.
GLib might cause a crash if `g_regex_match()` is fed by a non-utf8 string while `G_REGEX_RAW` is not set. I consider this as a bug because, first, GLib behaves inconsistently in such cases and, second, crashing instead of giving a false result is unacceptable. Anyway, in this commit, `G_REGEX_RAW` is used.
There were other ways of avoiding the crash like validating the strings by `g_utf8_validate()` or using `g_data_input_stream_read_line_utf8()` but, in their case, the search wouldn't be done in non-utf8 texts (correctly). Apart from valid texts with encodings other than utf8, sometimes searching for metadata in a PDF file, for example, is useful.
> Fix a crash on searching

- configure.ac
VALAC is set to "valac" if no suitable compiler was found. See
https://www.gnu.org/software/automake/manual/html_node/Vala-Support.html
> Fix detection of Vala compiler at configure time

- src/base/fm-templates.c
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1357213
When g_key_file_load_from_file(... , &error) fails,
the error contents is supposed to be set to error.
However actually reading g_key_file_load_from_file()
implementation shows that unless error is initialized to
NULL before calling g_key_file_load_from_file(), the
function leaves error unchanged.
So afterwards, g_error_free(error) tries to free uninitialized
pointer, which causes SIGABRT.
> Properly initialize GError with NULL

- src/modules/vfs-menu.c
libmenu-cache pkg-config file defines Cflags as:
Cflags: -I${includedir}/menu-cache
So #include <menu-cache/menu-cache.h> works only if ${includedir} is
included by default, e.g. standard locations. When libmenu-cache was
installed to a non-standard location ${includedir} is not part of the
default include path and #include <menu-cache/menu-cache.h> fails.
> Fixes FTBFS when libmenu-cache as installed to non-standard location

- data/libfm-pref-apps.desktop.in
LXQt comes with its own components to select default applications. These may not be in a too good shape right now but they exist and will always be available.
So the panel main menu in LXQt shouldn't provide yet another component to set default applications as this does not offer any advantage but is rather confusing only.
> libfm-pref-apps: don't show in LXQt

- src/actions/action.vala
On Fedora 26 (using vala 0.36.1), rebuilding libfm causes
a error as:
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/valac --thread --vapidir=./../vapi --pkg gio-2.0 --pkg posix --pkg libfm --vapi ./../vapi/fm-actions.vapi --header fm-actions.h   -C action.vala condition.vala profile.vala parameters.vala utils.vala
condition.vala:149.18-155.34: warning: unhandled error `GLib.Error'
condition.vala:192.8-193.40: warning: unhandled error `GLib.SpawnError'
action.vala:81.4-81.30: error: use `new' operator to create new objects
FileAction.from_keyfile(kf);
^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:144.4-144.34: error: use `new' operator to create new objects
FileActionMenu.from_keyfile(kf);
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Instead of using class name, "this" must be used here.
> Fix build error with vala 0.36.1

- src/base/fm-file-info.c
- src/base/fm-file-launcher.c
Fixes https://github.com/lxde/pcmanfm-qt/issues/449.
With this patch, clicking on a native desktop file opens a confirmation dialog instead of executing it. Trashed desktop files are only opened as text files and desktop files under menu (menu://applications/) are executed without prompt as before.
Recently, several users became worried about dangers of executing (native) desktop files without confirmation. I think they are right: promptless execution of desktop files is a significant security issue.
This PR will be followed by a small libfm-qt PR to have an appropriate confirmation dialog for desktop files.
> Treat desktop entries as executables

- src/base/fm-file-launcher.c
Fixes https://github.com/lxde/pcmanfm-qt/issues/592.
The FmFileInfo should be checked for its nullity before being reffed.
> Fix crash on launching nonexistent link targets

- src/gtk/fm-progress-dlg.c
This pull request adds tooltips for list of copying files, path and name of current file that may not to fit into the window.
> Added tooltips for attributes of copying files

- src/base/fm-thumbnail-loader.c
When browsing to the directory containing the thumbnails cache (typically ~/.thumbnails), and thumbnails are active, new thumbnails are generated for the cached files. The new thumbnails are created in the same directory, and they trigger the creation of even more thumbnails in a runaway process.
This PR still allows the thumbnails in that directory to be created and displayed, but does not save them on disk.
> Do not save thumbnails generated from the thumbnail cache directory

- src/gtk/fm-path-entry.c
Original report: https://bugzilla.redhat.com/show_bug.cgi?id=1437443
A pcmanfm crash is reproducible with the following step.
1.  launch a terminal (like lxterminal)
2.  On the terminal, execute ``$ cd /tmp``
3.  ``$ mkdir test``
4.  ``$ cd test``
5.  ``$ mkdir test1 test2``
6.  ``$ touch test.file.txt test2.doc test5.tgz``
7.  Then launch pcmanfm as ``$ pcmanfm`` (from the terminal). Then pcmanfm's URL bar should show "/tmp/test"
8.  On pcmanfm file list (or icon list), choose (one click) "test.file.txt" entry and type F2.
9.  Then "Rename File" dialog appears and the column shows "test.file.txt", with the part "test.file" highlightened. Select the whole string "test.file.txt" and copy it (with Ctrl-C, for example), then close the dialog with "Cancel".
10.  Now click pcmanfm URL bar …
> Fix segv on pasting large string when completion matches

- src/base/fm-thumbnail-loader.c
Since `generate_thumbnails_with_builtin()` is in thread, it may not have time to return a TRUE value in `fm-thumbnail-loader.c → generate_thumbnails()`, so that if there is an external image thumbnailer (like the PNG thumbnailer of gdk-pixbuf2 >= 2.36.1), a corrupted thumbnail will be imminent.
Please see that the above statement is just a speculation. However, this patch really prevents creation of corrupted thumbnails of PNG images with gdk-pixbuf2 >= 2.36.1. I also did some tests with a `gboolean`, to which the return value of `generate_thumbnails_with_builtin()` was assigned, and it always remained equal to its initial value, whether it was TRUE or FALSE.
> Prevent corrupted image thumbnails

- src/gtk/fm-folder-model.c
When showing the "extension" column, libfm displays the extension for directories named e.g. "folder.ext".
Extensions do not make sense for directories, so this PR blocks the detection of the extension for directories.
> Do not extract extension for directories

- src/job/fm-file-ops-job-xfer.c
- src/modules/vfs-search.c
Fixes https://github.com/lxde/pcmanfm-qt/issues/643
Instead of crashing (on pasting a file into the search folder), show an error message when the copy destination doesn't exist.
Also, `_fm_vfs_search_resolve_relative_path()` should always return NULL because relative paths don't make sense for the search and also because otherwise, a critical error will happen in `g_file_resolve_relative_path()` (G_IS_FILE will return FALSE for its first argument.)
> Handle null destination on copying

- data/ui/progress.glade
- src/gtk/fm-progress-dlg.c
This pull request adds a "Data transferred" field to the progress dialog that shows how much data is being transferred in the current operation:
This helps give the user a sense of the speed at which the operation is progressing.
> Add display of data transferred to progress dialog

- src/job/fm-file-ops-job-xfer.c
Fixes lxde/libfm-qt#137
For native and some virtual files display_name equals name of file, but not for Google Drive (see https://debarshiray.wordpress.com/2015/09/13/google-drive-and-gnome-what-is-a-volatile-path/ for explanations)
So, maybe better use display name of file as a target for copying from virtual to native.
Now all names work correctly, also for nested directories.
I am not sure, that my changes don't brake some virtual protocols, i test only for google-drive, samba, ftp.
> Fixes badnames for files, copied from Google Drive

- src/base/fm-path.c
Fixed a problem where if the home directory path and desktop directory path are
the same, desktop path would get corrupted. Without the fix, libfm will read
garbage from memory and treat it as a desktop path.
> Fix memory access error if home path == desktop path

- src/base/fm-file-info.c
lxde/libfm#21 added a security measure to prevent auto-execution of
possibly untrusted `*.desktop` files, with a hard-coded exception for
.desktop files found under `/usr/share` (e.g. `/usr/share/applications`)
as it is under system control, to mitigate user inconvenience.
This effectively broke LXDE under platforms that default to a different
path for packages/software installed by the (privileged) system
administrator, as now every interaction prompts users to choose between
launching or viewing the `.desktop` target in question.
This patch adds `/usr/local/share` to that list of exceptions, which is
the default location for system-controlled, non-1st-party applications,
on many platforms/distributions, such as FreeBSD.
(Obviously this is all with regards to `/usr/local/share` and not …
> Also treat /usr/local/share/ as trusted for *.desktop files

- src/gtk/fm-progress-dlg.c
When a large single file is being transferred, the value for the amount of data transferred shown on the progress dialog stays at 0 bytes. This is because there are two values provided from a file operation - the number of bytes transferred in all previous completed files, and the number of bytes transferred in the current file. These values need to be added together to compare correctly against the total - at present, only the number of bytes transferred in previous completed files is shown.
> Fix value for amount of data transferred

- src/gtk/fm-cell-renderer-text.c
This causes the height of the text cells to be correct on GTK 3. Else the bottom part of the text would be cut off.
> Always set preferred height in fm-cell-renderer-text

- src/base/fm-thumbnail-loader.c
The thumbnail directory should be created where user-specific
non-essential (cached) data should be written rather than in the
user's home directory.
This addresses github issue #57.
> Create thumbnails according to the XDG Base Directory Specification

- src/base/fm-action.c
- src/base/fm-app-info.c
`g_app_launch_context_get_display` returns `$DISPLAY` on X, but `$WAYLAND_DISPLAY` on Wayland. When then setting `$DISPLAY` to what `g_app_launch_context_get_display` returns on Wayland, it will cause it to not be able to launch X-only apps, because `$DISPLAY` will then contain an invalid X display (namely the name of the Wayland socket).
Setting `$DISPLAY` is unnecessary anyway as far as I could tell, because the launched app will inherit the environment variables from its parent. In order for e.g. PCManFM to be launched on X, it will need `$DISPLAY` to be set, so it will also give the correct `$DISPLAY` to the launched app.
> Don't set $DISPLAY

- src/gtk/exo/exo-icon-view.c
- src/gtk/fm-dnd-dest.c
- src/gtk/fm-standard-view.c
gcc14 now defaults to -Werror=incompatible-pointer-types . To support this, cast GTK related objects for assignment properly.
Fixes #100 .
> FIX: support gcc14 -Werror=incompatible-pointer-types

- src/gtk/exo/exo-icon-view.c
I tried building for gtk3, and the background color was wrong (it was the same as the toolbars - see attached picture, left side). This is how I fixed it (result on right side). I can make changes if required for merging.
> Fix background color with GTK3

- src/base/fm-config.c
- src/base/fm-config.h
The following 2 commit:
https://github.com/lxde/libfm/commit/b0545e0e7bd347dbb8001c153f8bd46718d0c852 https://github.com/lxde/libfm/commit/2854a4ce01f1e2868f2fa2f453eca5fe3fd8339c broke libfm.so ABI because this changed the size of `struct _FmConfig` .
Restore libfm.so ABI compared to before.
Fixes #104 .
> Restore ABI for libfm.so

- src/base/fm-dummy-monitor.c
C23 now regards function declaration without a parameter list as that with no parameter (i.e. having `(void)`).
Specify parameter list explicitly to make code C23 conformant.
Closes #106 .
> FIX: function argument fix for C23 conformance
